#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Portfolio Seonghee Min

  Birth 1993/07/28 <br/> Based in Incehon, Republic of Korea <br/> <br/> 
  Adobe Photoshop <br/> Adobe Illustrator <br/> Adobe After Effects <br/> Adobe Premiere Pro <br/> <br/> 
  ✨Thanks for coming✨

contact: >
  # Contact

  You may contact me [through my email](mailto:heeemazination@gmail.com) <br/>
  And You can also watch my artwork on instagram \(Please click the icon at the bottom\)
#-------------------------------
# Work Section

projects:
- {name: 'SM TOWN <br/> @coexartium', folder: 'proj-1', file: 'projects/proj-1.html'}
- {name: 'Kakao Pay', folder: 'proj-2', file: 'projects/proj-2.html'}
- {name: 'Born to be <br/> Hero ', folder: 'proj-3', file: 'projects/proj-3.html'}
- {name: 'Travel Alone', folder: 'proj-4', file: 'projects/proj-4.html'}
- {name: 'Youtube', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/heeemazination/'}
- {icon: 'envelope', link: 'mailto:heeemazination@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
